### PR TITLE
Use mb_strtolower function for generated report filenames

### PR DESCRIPTION
**Pull request by adevade**
Hopefully fixes bug in introduced in PR #27

### CODE REVIEW

**Comment by anuko** [comment]
Unless I am missing something, it does not seem to fix the problem with either Hebrew or Russian languages.

**Comment by Adevade** [comment]
hebrew_russian

This is what I get when I export with the language set to Russian or Hebrew.

**Comment by anuko** [comment]
CSV and XML files are downloaded properly.

The problem with PDF exports appears to be TCPDF class related. Tried with Google Chrome and Firefox on Ubuntu, the $filename shows up correctly in the debugger, but this line #410 in topdf.php:

$pdf->Output($filename.'.pdf', 'D'); // D is for downloads.

produces a file name for download without the first part:

missing_report_title

Have you tried PDF exports with TCPDF installed? If so, what may be different in my test install?

**Comment by anuko** [comment]
Did you have a chance to investigate whether TCPDF class can be fixed / updated to have the issue resolved? Just wondering.

**Comment by Adevade** [comment]
Sorry! Busy week at work! 

It seems to be an error with the PDF library. 
I tried commenting out [line 333 in topdf.php](https://github.com/Adevade/timetracker/blob/bug/fix-report-filenames/topdf.php#L333), and that did nothing. I then tried commenting out [line 401 in the same file](https://github.com/Adevade/timetracker/blob/bug/fix-report-filenames/topdf.php#L333), and it seems to work fine for me in latest Chrome on Win10. 

-----

It seems like a new version of the library is in development [here on GitHub](https://github.com/tecnickcom/tc-lib-pdf)

**Comment by anuko** [comment]
Closing. No longer relevant.

**Pull request closed without merging**
