### PR TITLE
Added an option allowing selected task to have 0 entered as duration. 

### PR DESCRIPTION
**Pull request by avidenic**
I've added a feature where team leader can select tasks for which it is allowed to enter 0 as duration. 

I've also refactored code related to a log record. All validation is now in one class, which improves code maintainability. 

Please review changes and suggest any improvements. 

Regards

### CODE REVIEW

**Comment by anuko** [comment]
Can you explain why 0 duration tasks are needed? Why only certain tasks? Why not all tasks, or even projects, and time-only records.

**Comment by avidenic** [comment]
At the moment we need to allow some workers to enter 0 for annual leave/sick leave, they're billed differently at the end of the month depending also on type of contract with the worker.

**Comment by anuko** [comment]
Thanks for the explanation. I made 0 durations "legal" instead in the main branch as of Time Tracker version 1.9.29.3523. Hopefully it accomplishes your business requirement, while at the same time keeping things reasonably simple.

**Comment by avidenic** [comment]
Thanks. Do I change this pull request to include only refactoring?

**Comment by anuko** [comment]
> Thanks. Do I change this pull request to include only refactoring?

This seems like a good idea. Since refactoring is a complex ongoing process, and apparently there are many ways to do it, I suggest keeping refactoring pull requests small in scope.

**Pull request closed without merging**
