### PR TITLE
patched openldap to work with member_of groups

### PR DESCRIPTION
**Pull request by junes**
Hi! I really like timetracker as a simple but efficient time tracking tool. I have been using it for many years in various organizations. Most of them use OpenLDAP. Basic authentication has always worked well, but checking the group membership(s) did not. So here is a patch to fix this. Thank you so much for all your good work!

### CODE REVIEW

**Comment by anuko** [comment]
What is the reason for removing this part:

      // check if the user specified full login
      if (strpos($login, '@') === false) {
        // append default domain
        $login .= '@' . $this->params['default_domain'];
      }

**Comment by junes** [comment]
Hi and thank you for getting back to me!

Actually it is not deleted but just moved a bit lower in the code to line 281. The reason for this is that the pure login credentials (without the `@domain` appendix) is needed as part of the search (`$filter = 'uid='.$login;`) in line 222. I hope this helps.

**Comment by anuko** [comment]
Thanks for clarifying it. I merged it and then cleaned up some comments and styles. Hopefully without breaking anything. But if I did please let me know.

**Comment by junes** [comment]
Thank you very much! I tested your latest version and it all works as desired: user can login if member of group(s); login fails if not.  :100: 

Please allow me to add two more comments:

1. As the OpenLDAP world allows for a huge variety of configurations, including the option to choose a different login attribute to identify the users, it might be useful to extend the config parameters and add  a `user_login_attribute = uid` default.

2. The term `base_dn` in LDAP is a relatively established term for the Base DN setting, which specifies the root for searches in the directory tree. Usually this matches the root of the LDAP domain. But in your case, what is needed is the `user_base_dn`, to specify the exact LDAP branch that is appended to the the `${user_login_attribute}.'='.${login}` string, to reflect the user's fully qualified Distinguished Name (DN) (see line 192 of your code). So I would like to suggest to rename `base_dn` in `user_base_dn`.

**Comment by anuko** [comment]
Your suggestions make sense.  Feel free to submit a pull request to accommodate them. I hope we will not break AD authenrtication.

**Pull request merged**
