### PR TITLE
basic Estonian translation

### PR DESCRIPTION
**Pull request by antirais**
Add basic Estonian translation.

### CODE REVIEW

**Comment by anuko** [comment]
Thanks for providing this patch. I am going to review it and perhaps add some comments. There are a few things that may need further addressing. I'll try to go over the entire file to determine the best course of action.

**Comment by anuko** [comment]
Well, I am about 30% through, and hit what seems to be an incorrect translation.

`'label.schedule' => 'Ajaarvestus', // Incorrect translation? This means "cron schedule". Perhaps we need to add a comment explaining this label.`

It is best not to merge this PR as is, but as individual partial commits with clarifying comments, which I plan to do shortly. When I am done I'll add a comment here.

**Comment by antirais** [comment]
> Well, I am about 30% through, and hit what seems to be an incorrect translation.
> 
> `'label.schedule' => 'Ajaarvestus', // Incorrect translation? This means "cron schedule". Perhaps we need to add a comment explaining this label.`

Dictionary translation is "ajakava". I took the liberty to change the translation a bit, to be closer to functionality and the intent of the action behind it, but still tried to be exact as possible. 

> It is best not to merge this PR as is, but as individual partial commits with clarifying comments, which I plan to do shortly. When I am done I'll add a comment here.

Sounds good.

**Comment by antirais** [comment]
> `'label.schedule' => 'Ajaarvestus', // Incorrect translation? This means "cron schedule". Perhaps we need to add a comment explaining this label.` 

Updated translation to reflecting that.

**Comment by anuko** [comment]
Thanks for all this work.

I integrated most of proposed changes into master branch as a set of several commits with a few fixes and exceptions.

I kept label.schedule as Ajakava as some users are not aware for cron at all.

I put TODO comments and some clarifications into the file in areas that may need an improvement, in my opinion.

I changed capitalization of some labels, hopefully improving things.

I also kept menu.export as Eksport to keep menu compact.

Feel free to review and submit further improvement in a separate pull request.

Closing this PR now, as most of the work is done, thank you very much!

**Pull request closed without merging**
