### PR TITLE
move edit link to a different column in order to free up horizontal s…

### PR DESCRIPTION
**Pull request by thurt**
…pace on mobile

Also removes delete column for the inactive users table 

issue: #8

### CODE REVIEW

**Comment by thurt** [comment]
Here are a few pics from my browser. There are obviously some width issues left to resolve but that should probably be in a different PR.
users-w-edit
expenses-w-edit
projects-w-edit

This PR is ready to merge unless you see any problems related to the moving of the edit link.

**Comment by anuko** [comment]
The mobile/users.php page in this patch has a problem of missing manager name when accessed by a co-manager, see attached screenshot.

missing_manager_name

**Comment by thurt** [comment]
Thanks for noticing that. I will try to get that fixed tomorrow

**Comment by thurt** [comment]
Hi anuko,

Sorry I got busy on other things the last two weeks. I rebased this PR to include all the new master updates and I added a commit which fixes the missing manager name when logged in as co-manager. 

Let me know if you see anything else that needs work. I will keep working on making PR's till we can get things looking good.

**Comment by anuko** [comment]
Please see the issue https://github.com/anuko/timetracker/issues/17 - some mobile pages are not horizontally centered.

**Pull request merged**
