### PR TITLE
 Suggested revision to expenses.php and expense_edit.php

### PR DESCRIPTION
**Pull request by kimkeown**
I wish to express my appreciation of the terrific open source Time Tracker application.  As a small contribution to the program, I would like to suggest a couple of simple changes that have worked for me. 

The first is increasing the expenses.php (and expense_edit.php) Item text input to allow a detailed description by adding the time.php note_input box format. As note_input_height may also be controlled within config.php, it can be adjusted from there as well. 

The second is adding a TimeDate stamp to footer.tpl. The TimeTracker has no clock (to my knowledge) beyond the timer function. Although the calendar is very user-friendly it doesn't provide a long-format date, which is useful for application viewing and reports. The footer contains an empty paragraph, and TimeDate works nicely in that void and is automatically centered within the existing td styles. It could also easily be placed under the spacer to preserve the existing formatting.

I hope these suggestions are of value. Thanks again for the excellent program!

Sincerely,
Kimberly Keown

### CODE REVIEW

**Comment by anuko** [comment]
It looks like you may be assuming that the server and user browsers are in the same timezone, which is not the case (usually). Footer time and date from Smarty / PHP may be wrong from user's perspective. Actually, Calendar gadget had proper browser time updated by Javascript before, was removed during refactoring to simplify things.

**Comment by kimkeown** [comment]
You're right, the settings use the server location, or actually php.ini date.timezone="". Timezone display clarifies the setting, however date/time display from a different location would likely annoy the user.

A few possible workarounds beyond the removed JS gadget: 

- A starting point may be an old 2005 Smarty plugin mydate. 
http://www.smarty.net/forums/viewtopic.php?t=4300
plugin_mydate_smarty

- Additional posts which may or may not be applicable:
http://www.smarty.net/forums/viewtopic.php?t=7630&sid=27a30783fc3f0512064f0270a1689458
http://www.smarty.net/forums/viewtopic.php?t=8309&sid=ae7a909b819c6e9086b407f19755c321

- Integrate PHP timezone setting and add timezone and date display options to config file (with reference to possible values per http://php.net/manual/en/timezones.america.php):
ex. date_default_timezone_set("America/New_York"); echo date("l, F, d, Y ~ h:i A T");

- The time.php timer does not specify a timezone (perhaps a feature request?). However, it appears to use the browser settings to timestamp the entries. I don't know enough about it to understand how it's written, and perhaps it was part of the removed calendar gadget, so I will merely overstate the obvious and suggest it could be adapted to include a template datetime stamp. 

Smarty DateTime values for reference:
http://www.smarty.net/docsv2/en/language.modifier.date.format.tpl
http://www.smarty.net/docsv2/en/tips.dates.tpl
date_format_smarty

**Comment by kimkeown** [comment]
Apologies for close/open. I hit the wrong button.

**Comment by kimkeown** [comment]
Here's a better timezone page:
http://php.net/manual/en/timezones.php

**Comment by anuko** [comment]
item_size field in database (tt_expense_items table) is currently 255 characters, not 800. So, 800 is not going to work. I am going to increase maxlength to 255, and use NOTE_INPUT_HEIGHT as you suggested for now.

In case 255 is not enough feel free to submit another pull request and adjust sql accordingly.

**Comment by anuko** [comment]
Integrated the change (excluding footer.tpl) in Time Tracker 1.9.31.3541.

**Comment by kimkeown** [comment]
That's terrific, I'm happy the expense note modification will be of value! I certainly overlooked checking the table's database setting and am very glad you noticed the incongruity. I'll test out a longer text or varchar setting and likely make the database revision request.

**Comment by kimkeown** [comment]
Hello, 

It's been some time since I proposed the addition of a clock to the Anuko Timetracker application footer, and as the topic of how to implement a clock was unresolved without a workable solution I wanted to follow-up: https://github.com/anuko/timetracker/pull/22#issuecomment-250049905.

In the interim of the pull request, I've written a function for a JavaScript clock inspired by a question posed in StackOverflow that received a response to try JavaScript [Date.prototype.toLocaleDateString()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString). 

My adaptation of the toLocaleDateString() clock uses the browser timezone via client computer timezone and incorporates the W3 Schools JavaScript 'Timing Clock' tutorial to enable the clock to be updated in real time without refreshing the browser: https://www.w3schools.com/js/tryit.asp?filename=tryjs_timing_clock.

The StackOverflow question and my response with the JavaScript clock code snippet may be viewed at:
https://stackoverflow.com/a/41306789/6600846.

I've also added a < noscript > PHP clock that prints the date/time with GMT timezone if JavaScript is disabled (the static date/timestamp only updates on page refresh). A custom timezone value could similarly be defined. I've used the clocks on my websites for several months and they have functioned perfectly.

However, the Timetracker Smarty Template Engine does not permit standard PHP functions in the designated suggested location, the template footer. As I am less versed in Smarty format,  I've created a preliminary script that would implement the JavaScript clock using Smarty -> PHP constants and smarty.now date/time format.  

I've tested the script with a PHP webpage, however I have not tested it with Timetracker itself as my attention has been focused elsewhere; and as a previously noted JavaScript clock was removed there is some question as to whether a clock would be integrated into the application and if so whether to incorporate standard PHP, Smarty PHP, or both for the < noscript > clock, as the Timetracker configuration file uses PHP constants while the Smarty Template Engine disregards PHP tags and deprecates {php}.  (The provided script uses an accepted, although less-than-ultimate, mix-match of both by accessing PHP constant values with {$smarty.const.value}: https://www.smarty.net/docsv2/en/language.variables.smarty.tpl.) Therefore, I was unable to double-check the Smarty functions for formatting or parse errors. 

	 Date: 07/27/2017
	 Title: Kimberly Keown Website Design JavaScript Clock script intended for integration with Anuko Timetracker PHP Application
	 Authored by: Kimberly Keown | Kimberly Keown Website Design | https://github.com/kimkeown
	 Application: Anuko Timetracker PHP Application | Based on Smarty Template Engine | https://github.com/anuko/timetracker
	 Reference: https://www.smarty.net/best_practices | https://www.smarty.net/docsv2/en/language.variables.smarty.tpl | https://www.smarty.net/docsv2/en/language.modifier.date.format.tpl
	 Acknowledgements: https://stackoverflow.com/a/41306789/6600846 | https://www.w3schools.com/js/tryit.asp?filename=tryjs_timing_clock

    
	 <?php
	 /* JS Clock Constants */
	 /* timetracker/WEB-INF/config.php.dist
	 DateTimestamp constants used for <noscript> Smarty PHP clock if JavaScript is not enabled. */
	 /* Default Timezone */
	 date_default_timezone_set("America/New_York");

	 /* Prefix for JavaScript Clock.*/
	 define('JS_CLOCK_PREFIX', 'Today is ');
	 // Other values:
	 /* No prefix
	 define('JS_CLOCK_PREFIX', ''); */

	 /* Smarty Date/Time.
	 A mishmash of PHP/Smarty, however may be a simple initial workaround to customize or omit PHP <noscript> clock in lieu of enabled PHP functions or defined values using Smarty format.
	 Ideally $smarty.now|date_format will reference PHP date_default_timezone_set, else will use default Server timezone. */
	 define('JS_CLOCK_FORMAT', '{$smarty.now|date_format:"%A, %B %d, %Y ~ %I:%M %p %Z"}');
	 // Other values:
	 /* PHP Date/Time:
	 define('JS_CLOCK_FORMAT', date("m-d-Y @ H:i T")); */
	 /* PHP GMT timezone:
	 define('JS_CLOCK_FORMAT', gmdate("m-d-Y @ H:i T")); */
	 /* Omit <noscript> clock:
	 define('JS_CLOCK_FORMAT', ''); */
	 /* End JS Clock Constants */
	 ?>

	 
	 .jsclock {margin: 5px auto; font-size: 10pt; color: #000000;}
	 

	 
	 <div>
	 <script type="text/javascript">
	 /* function js_clock() and function jsclock_start() possibly could be added to a JavaScript function file,
	 such as js/strptime.js, and called from template. */
	 
	 /* Initialize function on page load to update clock in real-time | jsclock_start() could be called from <body onload="jsclock_start()" */
	 function jsclock_start() { js_clock(); }
	 window.onload = jsclock_start;
	 </script>

	 <div class="jsclock">
	 
	 {$smarty.const.JS_CLOCK_PREFIX}
	 
	 <span id="timedate"></span>
	 
	 <noscript><span>{$smarty.const.JS_CLOCK_FORMAT}</span></noscript>
	 </div>
	 </div>
	 
	 

Kindly share your thoughts upon reviewing the JavaScript Clock script.

Thank you,
Kimberly

**Pull request closed without merging**
