### PR TITLE
Update filename for exported reports to the users language

### PR DESCRIPTION
**Pull request by Adevade**
Now defaults to "report" in the users language, or English if the word isn't set, and also includes start date and end date for the generated report. 

{report}_{start_date}_{end_date}.xml/csv/pdf

### CODE REVIEW

**Comment by anuko** [comment]
It looks like a dot is missing in the PDF export before the pdf extension.

**Comment by Adevade** [comment]
You're right! It's fixed now!

**Comment by anuko** [comment]
The report name is missing in some languages such as Hebrew or Russian. Only the dates are in the downloaded file name, such as _2016-10-01_2016-10-31.pdf.

**Comment by Adevade** [comment]
I tried commenting out the string from the Swedish translation file, and it defaulted to using the English string.

**Comment by Adevade** [comment]
I think I got it now. Seems to be a problem with `strtolower()` on UTF-8 characters. Switched to [mb_strtolower](http://php.net/manual/en/function.mb-strtolower.php) (supported by PHP 4.3+) instead.

**Pull request merged**
