### PR TITLE
Added a plugin, where team leader can set monthly quota in hours

### PR DESCRIPTION
**Pull request by avidenic**
The plugin adds following functionality:

- Team leader can set monthly quota in hours for each month. If no quota is set, one is calculated from working days within a month
- Users than see their monthly sum of hours and how much are they under/over quota. 

Please code review and tell me if anything needs to be changed. I've taken the liberty to call this version 1.9.30 - if you do not like it, please suggest a different version. 

Regards

### CODE REVIEW

**Comment by anuko** [comment]
This code has a problem: the updated database structure does not distinguish quotas between teams, therefore a manager for one team can change quotas for all teams. Other issues are implementation specifics such as magic numbers 1990-2040, 8-hour work day, and a database error when not all fields are filled in. Why is it an error not to specify a quota for a given month? Why does it use a pre-calculated quota when one does not provide a quota, instead of not using a quota at all, or actually seeing in the UI that it is going to be pre-calculated as per 8-hour work day? It looks like it is difficult to come up with a generic solution, though. Overall, I think the plugin requires at least some re-design. Maybe together with how holidays are handled in the app, as the way they are handled now is not good. For example, if there existed a way to specify holidays per team, and define work day duration, perhaps the config UI is not needed at all and you can go with pre-calculated, based on holidays.

**Comment by anuko** [comment]
Perhaps, a better way to address the problem is to write a separate Holidays plugin where a team manager can specify holidays for multiple years. Than do a very simple Quota pluign which uses the defined holidays and pre-calculates quotas based on work day duration for team (which will default to 8 hours). However, I am not familiar with the business problem. this is just a suggestion.

What I am worried about is future code maintenance.

**Comment by avidenic** [comment]
Thank you for your answer! 

Yes, the holiday implementation is something that worried me as well, specially because in some countries where they use religious holidays as state holidays. Religious holidays are often tied to Lunar cycle, meaning they're not a fixed date each year. 

That is the reason an empty monthly quota is not considered an error. Logic behind is, that until holidays are fixed so they're stored in DB, for most months holidays in config are sufficient and monthly quota can be calculated. I would leave it as is for now, but would maybe add a comment about the functionality and the idea behind it i.e. - empty quota meaning automatic calculation. In step 2, where holidays are stored in DB, this part would also need to change (read holidays from DB). 

I will remove magic numbers and add them to config. 

I will also add team specific monthly quotas. 

Otherwise I would leave plugin as is - overriding monthly quota is needed in some cases, regardless of holidays i.e. there are international companies who do not observe national holidays, but give each employee a day a month he/she can select as a "holiday". In any case, this was meant more as a help to a user rather than a strict quota =)

I'll implement the proposed changes and will inform you when they're ready. Thank you for your time and your input!

**Comment by avidenic** [comment]
I've changed code to reflect what we debated. Please review it.

**Comment by anuko** [comment]
Quota calculation algorithm seems to have a problem when we are just over a quota less than 1 hour in total. For example, when I set daywork_hours to 1, this gives me 20 work hours in a month of July. Then log 20:30 hours, which is half hour over quota. The plugin reports that we are under quota, when in fact, we are half hour over it. The fromMinutes functions needs a fix. Also, using "abs" in what seems to be a general purpose function does not seem right. I'll stop any further refactoring until this issue is fixed.

**Comment by anuko** [comment]
There is currently an open issue #47 for non integer working hours in some situations. You may want to look at this to see if we need to fix this.

**Pull request merged**
