### PR TITLE
Fix initial sql statements

### PR DESCRIPTION
**Pull request by FrankGiesecke**
* Fix initial mysql statements
* Fix check for LDAP extension
* Provide docker for development purposes
  Create a simple docker image containing the necessary extensions to run anuko time tracker.
  Add a docker composition to start a mysql database and an apache with php.
  All this will be controlled using GNU make.

### CODE REVIEW

**Comment by anuko** [comment]
Thanks for the patch. I fixed ldap check as proposed.

With regards to backticks - we should perhaps stay away from them altogether as they are non standard, to make porting easier for someone who may want to use another DB eventually (not MySQL),

There is also a problem with auto_increment ids, as DELETE would not change LAST_INSERT_ID, and then an INSERT INTO would ignore the ids supplied, and just use the next, therefore such changes are not good, unless I am missing something.

With regards do docker - this has to wait until better time. Perhaps after we finish with subgroups, which is taking a while.

If there are other specific bugs fixed in your patch that I am missing, please comment for a review.

**Comment by FrankGiesecke** [comment]
Thanks for your reply.

As the mysql file contains a lot of reserved key words, it will fail without the backticks. I've tested this with docker and mysql 5.6.
Therefore, porting the queries to an other database system (e.g. Postgres) will not be possible as easy.

I would be appreciated if you also pick these fix into the master.

**Comment by FrankGiesecke** [comment]
Sadly to read your decision about docker. I've added this to be able to contribute.
It should be only used for development purposes.

If you change your opinion about this, I would also be appreciated to find the docker config for development in the master branch ;)

**Comment by anuko** [comment]
Well, I included my version of a Dockerfile and docker-compose.yml in my last 3 commits. Apparently not exactly how it was suggested, but something usable, at least to start with. I tried to keep things simple for now. If there are issues with the existing files please comment. I am willing to research this further to fix bugs and address issues. LDAP extension install needs a test, by the way.

**Comment by anuko** [comment]
Closing as important issues raised here are addressed as individual commits. Specifically, development Docker composition is there (although bugs are likely). I omitted make command stuff, as it seemed too specific to me for general availability. We may reconsider this later is there is more demand. I hope this provides something useful to start and move forward with and maintain. If there are specific issues or concerns or something is not working (LDAP?) please let us know. Thanks!

**Pull request closed without merging**
