### PR TITLE
show custom field on time.php

### PR DESCRIPTION
**Pull request by danklee19**
Have a look to: https://www.anuko.com/forum/viewtopic.php?f=4&t=1748

sorry for trying and testing...something went wrong

### CODE REVIEW

**Comment by anuko** [comment]
While this apparently solves the immediate problem reported in the forum, there are other design issues to consider.

- Look at reports, currently a note field is printed underneath a row, which allows for some more room for other columns, especially with long notes. This is out of sync with the current time page design.
- Reports can be configured to display fields as desired, for example, you can switch off not needed columns.
- Time page is currently not configurable, imagine a user with clients enabled, projects and tasks enabled, start, finish, and duration, as well as note, and now a custom field - already too much competition for space without an option to switch anything off or on. What do we do when there are 3, or 5 custom fields?
- There is also a week view, with its own design issues.
- Mobile pages.

All of the above needs to be looked at and addressed together, design-wise, so that there is more consistency between various views.

**Comment by anuko** [comment]
I am going to replace the Edit, Delete, and Files links (attachments) with icons instead of words, which should ease up space demands on tables.

I am also thinking about making fields that show up on the time page (and perhaps others) group-configurable (on the Group tab).

Perhaps then we could incorporate this PR somehow, conditionally (if selected). Any better ideas?

**Comment by danklee19** [comment]
Is it neccessary to make time page configurable? I think that's a lot of work.
In my opinion the time records on time page (time.php) are only a short overview and for further details you can use reports. So there can different designs on report and time page.

competition for space: That's a result of limited table width (720px). In my installation I extended the table width to 900px. And I'm testing a layout without nested table-tags beginning at ""

Maybe there is another way in beginning on some pages to separate layout (new CSS-files) and content (*.tpl)...we have to find some volunteers for testing :-)

**Comment by anuko** [comment]
I replaced the Edit text link with an icon. I reviewed the commit again, and see a problem related to Custom field being potentially of at least 2 types at the moment (dropdown and text), which are handled differently. Current commit handles only one type and, if I am not missing something, will display nothing for another type.

Best to handle both types correctly and also anticipate further extension of custom fields to other types, and also more than 1 custom field (which may be a more elaborate design effort).

See ttReportHelper::getItems for an example of a query to obtain cf_1 for reports.

**Comment by danklee19** [comment]
OK, I have looked and retraced mentioned class. It's more complicated than I thought. Timetracker has various possibilities 👍 
For a consistent code is it better to include customfield-plugin in ttTimeHelper?

**Comment by anuko** [comment]
At this time we need to handle 2 available types of custom fields correctly (without an extra plugin).

I am planning to do work on configuration options soon on what to include in output, also whether or not the note should occupy a separate row.

**Comment by anuko** [comment]
This pull request is missing a required change in getRecordsWithFiles. I re-wrote this code in commit https://github.com/anuko/timetracker/commit/870ef02e00ccf3c54edd893bfa84cfb4d692ac0a with hopefully less problems.

**Pull request closed without merging**
