### PR TITLE
Update fr.lang and Fix navigation to Puncher

### PR DESCRIPTION
**Pull request by Ben0it-T**
Update fr.lang

Fix navigation to Puncher via the link on Time page and Week page

### CODE REVIEW

**Comment by dalers** [comment]
Hi @Ben0it-T very glad to see someone cares about TimeTracker. Personally I am more of a user, and emailing invoices and reports also seems to be broken (PHP 8.x iiuc). I had a  conversation with Anuko last January and they wanted to continue maintaining, but today it seems unlikely. Are you doing more work? I'm thinking I should follow you now instead of Anuko. What are your plans?

**Comment by Ben0it-T** [comment]
Hi @dalers. I use timetracker for my personal use. I don't use all features and plugins
I only plan to implement two or three features: option to store sessions in database, option to use something other than md5 to store password.

**Comment by dalers** [comment]
I browsed the other forks and it seems no one else is doing any maintenance - let alone sending pull requests. I will pull from your repo next time I update if Anuko hasn't merged your pull requests (I don't hold much hope. I can help with testing release candidates for you if you like, just let me know.

**Comment by Ben0it-T** [comment]
Reported in 
- #140 
- #141 
- #142

**Pull request closed without merging**
